project_name: nv

before:
  hooks:
    - go mod tidy

builds:
  - <<: &build_defaults
      binary: nv
      main: ./cmd/nv/
      env:
        - CGO_ENABLE=0
      ldflags:
        - -s -w -X github.com/jcouture/nv/internal/build.Version={{.Version}}
    id: macos
    goos: [darwin]
    goarch: [amd64, arm64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64, arm, arm64]

upx:
  - enabled: true
    goos: [darwin, linux, windows]
    compress: best
    lzma: true
    brute: true

signs:
  - cmd: cosign
    stdin: "{{ .Env.COSIGN_PASSWORD }}"
    args:
      - "sign-blob"
      - "--key=env://COSIGN_PRIVATE_KEY"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: all

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - repository:
      owner: jcouture
      name: homebrew-nv
    folder: Formula
    homepage: https://github.com/jcouture/nv
    description: Lightweight utility to load context specific environment variables
    test: |
      system "#{bin}/nv"
