project_name: nv

before:
  hooks:
    - go mod tidy

builds:
  - <<: &build_defaults
      binary: nv
      main: ./cmd/nv/
      env:
        - CGO_ENABLE=0
    id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
  
  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64]

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  -
    tap:
      owner: jcouture
      name: homebrew-nv
    folder: Formula
    homepage:  https://github.com/jcouture/nv
    description: Lightweight utility to load context specific environment variables
    test: |
      system "#{bin}/nv"